notifications:
  email: false

language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
before_script:
  - pip install -r tests/requirements.txt
  - py.test tests/full_tests.py
script:
  - coverage run -m unittest -v tests.full_tests
after_success:
  - coveralls
  - sh make.sh